title: "Raphaël Romand-Ferroni"
description: "Data Scientist"
theme: jekyll-theme-cayman

# Navigation
header_pages:
  - about.md
  - experience.md
  - projects.md
  - contact.md

sass:
  style: compressed
